### ISSUE TITLE
Unexpected sizes in training code?

### ISSUE THREAD

**Issue by joshmyersdean** [TACJu/Compositor#1]
Hello!

Thank you for releasing this and with thorough instructions! I just went to try training the DeepLab variant (with 1 gpu) and got the following error

```bash
Traceback (most recent call last):
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/train_net.py", line 334, in <module>
    launch(
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/tmp/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/train_net.py", line 328, in main
    return trainer.train()
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/tmp/detectron2/detectron2/engine/defaults.py", line 486, in train
    super().train(self.start_iter, self.max_iter)
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/tmp/detectron2/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/tmp/detectron2/detectron2/engine/defaults.py", line 496, in run_step
    self._trainer.run_step()
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/tmp/detectron2/detectron2/engine/train_loop.py", line 494, in run_step
    loss_dict = self.model(data)
  File "/projects/jomy5901/software/anaconda/envs/compositor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/compositor/compositor_model.py", line 232, in forward
    losses = self.criterion(outputs, targets)
  File "/projects/jomy5901/software/anaconda/envs/compositor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/compositor/modeling/criterion.py", line 386, in forward
    losses.update(self.get_loss(loss, outputs, processed_targets, prefix='part_'))
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/compositor/modeling/criterion.py", line 283, in get_loss
    return loss_map[loss](outputs, targets, prefix=prefix)
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/compositor/modeling/criterion.py", line 217, in loss_labels
    losses = {prefix + "loss_ce": focal_cross_entropy_loss(src_logits, target_classes, pq_loss_class_weight)}
  File "/projects/jomy5901/Compositor/Compositor_kMaX-DeepLab/compositor/modeling/criterion.py", line 46, in focal_cross_entropy_loss
    loss = F.cross_entropy(pred, gt, reduction="none") # B x N
  File "/projects/jomy5901/software/anaconda/envs/compositor/lib/python3.9/site-packages/torch/nn/functional.py", line 2824, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected target size [16, 30], got [16, 42, 30]
```

Do you know why this may occur?

Thank you!

**Comment by joshmyersdean** [comment]
It looks like these shapes are intentional when looking at the code, although cross entropy does not support 3D logits -- could you expand on how you're passing these in?

**Comment by TACJu** [comment]
Hi Josh,

On my side I've never encountered such problem so I don't know why this may occur for now. I also re-test the code and it is directly runnable in my environment. Could you please provide more details or why do you think these shapes are intentional so I can take a deeper look into it? Also, do you encounter similar issue when training with multiple GPUs or using MaskFormer variant? Thanks!

**Comment by joshmyersdean** [comment]
Hi Ju,

Thanks for the quick response! I do not encounter this error with MaskFormer, but it looks like the criterions are set up differently. This is the line where it looks like the 3D shape is expected: https://github.com/TACJu/Compositor/blob/main/Compositor_kMaX-DeepLab/compositor/modeling/criterion.py#L45. 

I'm having some issues with multi-gpu training on our computing cluster but once that is fixed I can see if that resolves this issue.

Thank you!

**Comment by joshmyersdean** [comment]
I'm not sure why but this solved itself for me. Thank you!
